// <auto-generated />
using System;
using LifeTrader_AI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeTraderAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225153506_AddToolRuns")]
    partial class AddToolRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("LifeTrader_AI.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_ChatMessages_CreatedAtUtc");

                    b.HasIndex("PositionId");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("IX_ChatMessages_ThreadId");

                    b.ToTable("ChatMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChatMessages_Role", "[Role] IN ('system', 'user', 'assistant', 'tool')");
                        });
                });

            modelBuilder.Entity("LifeTrader_AI.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgEntryPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(0m);

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Currency")
                        .IsUnique()
                        .HasDatabaseName("IX_Positions_Symbol_Currency");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("LifeTrader_AI.Models.ToolRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_ToolRuns_CreatedAtUtc");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("IX_ToolRuns_ThreadId");

                    b.ToTable("ToolRuns", (string)null);
                });

            modelBuilder.Entity("LifeTrader_AI.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<decimal>("ExecutedPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Fees")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_Trades_ClientRequestId");

                    b.HasIndex("ExecutedAtUtc")
                        .HasDatabaseName("IX_Trades_ExecutedAtUtc");

                    b.HasIndex("PositionId");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("IX_Trades_Symbol");

                    b.ToTable("Trades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trades_Side", "[Side] IN ('BUY', 'SELL')");

                            t.HasCheckConstraint("CK_Trades_Status", "[Status] IN ('FILLED', 'PENDING', 'REJECTED')");
                        });
                });

            modelBuilder.Entity("LifeTrader_AI.Models.ChatMessage", b =>
                {
                    b.HasOne("LifeTrader_AI.Models.Position", "Position")
                        .WithMany("ChatMessages")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Position");
                });

            modelBuilder.Entity("LifeTrader_AI.Models.Trade", b =>
                {
                    b.HasOne("LifeTrader_AI.Models.Position", "Position")
                        .WithMany("Trades")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Position");
                });

            modelBuilder.Entity("LifeTrader_AI.Models.Position", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
